name: todoai_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  intl:
  flutter_localizations:
    sdk: flutter
  connectivity_plus: ^4.0.1
  dio: ^5.2.1
  http: ^0.13.6
  shared_preferences: ^2.1.2
  lottie: ^2.3.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: TodoAi-Bold
      fonts:
        - asset: assets/fonts/TodoAi-Bold.ttf

    - family: TodoAi-Book
      fonts:
        - asset: assets/fonts/TodoAi-Book.ttf

    - family: TodoAi-Medium
      fonts:
        - asset: assets/fonts/TodoAi-Medium.ttf
